SELECT * FROM CUSTOMER;
SELECT * FROM SALES;

-- 매출트렌드 분석
-- 기간별 매출 현황
SELECT DATE(INVOICEDATE)
, SUM(UNITPRICE * QUANTITY) AS 매출액
, SUM(QUANTITY) AS 주문수량
, COUNT(DISTINCT INVOICENO) AS 주문건수
, COUNT(DISTINCT CUSTOMERID) AS 주문고객수
FROM SALES
GROUP BY DATE(INVOICEDATE)
ORDER BY DATE(INVOICEDATE);   -- 305개

-- 국가별 매출 현황
SELECT COUNTRY
, SUM(UNITPRICE * QUANTITY) AS 매출액
, SUM(QUANTITY) AS 주문수량
, COUNT(DISTINCT INVOICENO) AS 주문건수
, COUNT(DISTINCT CUSTOMERID) AS 주문고객수
FROM SALES
GROUP BY COUNTRY;

